### ISSUE TITLE
Does not run in HTML5 Export 

### ISSUE THREAD

**Issue by ChristianTucker** [rayxuln/spine-runtime-for-godot#30]
When trying to run a project in HTML5 export that has spine runtime, following error is presented and project does not load.

GODOT 3.2.3 Stable 

I should add that I have built a template as the docs show here:
https://docs.godotengine.org/en/stable/development/compiling/compiling_for_web.html#building-export-templates

```
*ERROR**: Cannot get class 'SpineAtlasResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineAtlasResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineAtlasResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineAtlasResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineAtlasResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineAtlasResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineAtlasResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineAtlasResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineAtlasResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineAtlasResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineAtlasResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineAtlasResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineAtlasResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineAtlasResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineAtlasResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineAtlasResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineAtlasResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineAtlasResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineAtlasResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineAtlasResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineAtlasResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineAtlasResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineAtlasResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineAtlasResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineAtlasResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineAtlasResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineAtlasResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineAtlasResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: No loader found for resource: res://src/Actors/spine character 1 spine ready.atlas. TestProject.js:8:42051
   At: core/io/resource_loader.cpp:286:_load() - Method failed. Returning: RES() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineSkeletonJsonDataResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineSkeletonJsonDataResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineSkeletonJsonDataResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineSkeletonJsonDataResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineSkeletonJsonDataResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineSkeletonJsonDataResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineSkeletonJsonDataResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineSkeletonJsonDataResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineSkeletonJsonDataResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineSkeletonJsonDataResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineSkeletonJsonDataResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineSkeletonJsonDataResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineSkeletonJsonDataResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineSkeletonJsonDataResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineSkeletonJsonDataResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineSkeletonJsonDataResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineSkeletonJsonDataResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineSkeletonJsonDataResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineSkeletonJsonDataResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineSkeletonJsonDataResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineSkeletonJsonDataResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineSkeletonJsonDataResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineSkeletonJsonDataResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineSkeletonJsonDataResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineSkeletonJsonDataResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineSkeletonJsonDataResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineSkeletonJsonDataResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineSkeletonJsonDataResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: No loader found for resource: res://src/Actors/spine character 1 spine ready.json. TestProject.js:8:42051
   At: core/io/resource_loader.cpp:286:_load() - Method failed. Returning: RES() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineSkeletonDataResource'. TestProject.js:8:42051
   At: core/class_db.cpp:538:instance() - Condition "!ti" is true. Returned: 0L TestProject.js:8:42051
**ERROR**: res://src/Actors/Player.tscn:59 - Parse Error: Can't create sub resource of type: SpineSkeletonDataResource TestProject.js:8:42051
   At: scene/resources/resource_format_text.cpp:499:poll() - res://src/Actors/Player.tscn:59 - Parse Error: Can't create sub resource of type: SpineSkeletonDataResource TestProject.js:8:42051
**ERROR**: Failed to load resource 'res://src/Actors/Player.tscn'. TestProject.js:8:42051
   At: core/io/resource_loader.cpp:208:load() - Condition "err != OK" is true. Returned: RES() TestProject.js:8:42051
**ERROR**: Failed loading resource: res://src/Actors/Player.tscn. Make sure resources have been imported by opening the project in the editor at least once. TestProject.js:8:42051
   At: core/io/resource_loader.cpp:279:_load() - Condition "found" is true. Returned: RES() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineAtlasResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineAtlasResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineAtlasResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineAtlasResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineAtlasResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineAtlasResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineAtlasResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineAtlasResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineAtlasResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineAtlasResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineAtlasResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineAtlasResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineAtlasResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineAtlasResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineAtlasResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineAtlasResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineAtlasResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineAtlasResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineAtlasResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineAtlasResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineAtlasResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineAtlasResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineAtlasResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineAtlasResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineAtlasResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineAtlasResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineAtlasResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineAtlasResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: No loader found for resource: res://src/Actors/spine character 1 spine ready.atlas. TestProject.js:8:42051
   At: core/io/resource_loader.cpp:286:_load() - Method failed. Returning: RES() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineSkeletonJsonDataResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineSkeletonJsonDataResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineSkeletonJsonDataResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineSkeletonJsonDataResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineSkeletonJsonDataResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineSkeletonJsonDataResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineSkeletonJsonDataResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineSkeletonJsonDataResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineSkeletonJsonDataResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineSkeletonJsonDataResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineSkeletonJsonDataResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineSkeletonJsonDataResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineSkeletonJsonDataResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineSkeletonJsonDataResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineSkeletonJsonDataResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineSkeletonJsonDataResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineSkeletonJsonDataResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineSkeletonJsonDataResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineSkeletonJsonDataResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineSkeletonJsonDataResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineSkeletonJsonDataResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineSkeletonJsonDataResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineSkeletonJsonDataResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineSkeletonJsonDataResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineSkeletonJsonDataResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineSkeletonJsonDataResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineSkeletonJsonDataResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineSkeletonJsonDataResource'. TestProject.js:8:42051
   At: core/class_db.cpp:343:get_parent_class() - Condition "!ti" is true. Returned: StringName() TestProject.js:8:42051
**ERROR**: No loader found for resource: res://src/Actors/spine character 1 spine ready.json. TestProject.js:8:42051
   At: core/io/resource_loader.cpp:286:_load() - Method failed. Returning: RES() TestProject.js:8:42051
**ERROR**: Cannot get class 'SpineSkeletonDataResource'. TestProject.js:8:42051
   At: core/class_db.cpp:538:instance() - Condition "!ti" is true. Returned: 0L TestProject.js:8:42051
**ERROR**: res://src/Actors/Player.tscn:59 - Parse Error: Can't create sub resource of type: SpineSkeletonDataResource TestProject.js:8:42051
   At: scene/resources/resource_format_text.cpp:499:poll() - res://src/Actors/Player.tscn:59 - Parse Error: Can't create sub resource of type: SpineSkeletonDataResource TestProject.js:8:42051
**ERROR**: Failed to load resource 'res://src/Actors/Player.tscn'. TestProject.js:8:42051
   At: core/io/resource_loader.cpp:208:load() - Condition "err != OK" is true. Returned: RES() TestProject.js:8:42051
**ERROR**: Failed loading resource: res://src/Actors/Player.tscn. Make sure resources have been imported by opening the project in the editor at least once. TestProject.js:8:42051
   At: core/io/resource_loader.cpp:279:_load() - Condition "found" is true. Returned: RES() TestProject.js:8:42051
**WARNING**: Couldn't load external resource: res://src/Actors/Player.tscn TestProject.js:8:42051
   At: scene/resources/resource_format_text.cpp:175:_parse_ext_resource() - Couldn't load external resource: res://src/Actors/Player.tscn TestProject.js:8:42051
**ERROR**: Condition "!sdata.is_valid()" is true. Returned: 0L TestProject.js:8:42051
   At: scene/resources/packed_scene.cpp:140:instance() - Condition "!sdata.is_valid()" is true. Returned: 0L TestProject.js:8:42051
**ERROR**: Failed loading scene: res://src/Levels/TestLevel.tscn TestProject.js:8:42051
   At: main/main.cpp:1944:start() - Condition "!scene" is true. Returned: false TestProject.js:8:42051
Uncaught Error: undefined
```

**Comment by rayxuln** [comment]
You need to build the HTML5 export template first!

**Comment by ChristianTucker** [comment]
@rayxuln Hey rayxuln, if by building the template you mean the instructions here: https://docs.godotengine.org/en/stable/development/compiling/compiling_for_web.html#building-export-templates 

I have already done this :)

**Comment by ChristianTucker** [comment]
I found the error, it was a configuration issue, everything is working! Thanks for your efforts on this!
